
services:
  application:
    image: wt1-project-local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: "npm start"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/myapp
  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/templates:/etc/nginx/templates
      - ./container_logs/nginx:/var/log/nginx
      - ./public:/usr/share/nginx/html
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
      - NGINX_PROXY=http://application:3000
    depends_on:
      - application
    restart: always
  mongo:
    container_name: mongo-backend
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: myapp
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data_container:/data/db
      - ./seed:/docker-entrypoint-initdb.d